name: clang-tidy

on:
    pull_request:
    push:
      branches: [main]

jobs:
    clang-tidy:
        # https://packages.ubuntu.com/jammy/devel/ supports up to clang-15
        runs-on: ubuntu-22.04
        steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: configure
          run: |
            cmake -S . -B build build -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DEOB_ENABLE_CLANG_TIDY=ON
        # - name: configure and build
        #   uses: threeal/cmake-action@main
        #   with:
        #     options: "EOB_ENABLE_CLANG_TIDY=ON", "CMAKE_BUILD_TYPE=Release"]
        #     generator: Unix Makefiles
        #     c-compiler: clang-15
        #     cxx-compiler: clang++-15
