name: cppcheck

on:
    pull_request:
    push:
      branches: [main]


# https://github.com/marketplace/actions/cppcheck-action
# ^ is maybe an alternative worth exploring, but seems like 
# an older cppcheck version...
jobs:
    ubuntu:
        runs-on: macos-14
        steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: brew install cppcheck
          run: |
            brew install cppcheck
            echo "$(brew --prefix cppcheck)/bin" >> $GITHUB_PATH
            echo "$PATH"
        # - name: cppcheck
        #   uses: deep5050/cppcheck-action@main
        #   with:
        #     std: c++20
        #     enable: all
        #     other_options: >+
        #         --check-level=exhaustive
        #         --suppress=missingIncludeSystem
        #         -I include/
        #     github_token: ${{ secrets.GITHUB_TOKEN}}
            
        # - name: publish report    
        #   uses: mikeal/publish-to-github-action@master
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #     BRANCH_NAME: 'main' # your branch name goes here

        - name: cppcheck
          run: >-
            cppcheck --std=c++20 --check-level=exhaustive --enable=all 
            --suppress=missingIncludeSystem -i build -I include/ .
