name: cppcheck

on:
    pull_request:
    push:
      branches: [main]

# https://github.com/marketplace/actions/cppcheck-action
# ^ is maybe an alternative worth exploring, but seems like 
# an older cppcheck version...
jobs:
    macos:
        runs-on: macos-14
        steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: brew install cppcheck
          run: |
            brew install cppcheck
            echo "$(brew --prefix cppcheck)/bin" >> $GITHUB_PATH
            echo "$PATH"

        - name: cppcheck
          run: >-
            cppcheck --std=c++20 --check-level=exhaustive --enable=all 
            --suppress=missingIncludeSystem -i build -I include/
            --error-exitcode=1 .

        # - name: Publish Test Results
        #   uses: EnricoMi/publish-unit-test-result-action/macos@v2
        #   if: always()
        #   with:
        #     files: |
        #         cppcheck.xml
